spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: MICROSERVICE-ZUUL-GATEWAY
server:
  port: 9527
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  routes:
    aigouUser.serviceId: EMPLOYEE-PROVIDER
    aigouUser.path:  /employee/**
  ignored-services: "*"
  prefix: /aigou   # 访问前缀
  ---
  spring:
    profiles: dev
    application:
      name: MICROSERVICE-ZUUL-GATEWAY
  server:
    port: 9527
  eureka:
    client:
      service-url:
        defaultZone: http://localhost:7001/eureka
    instance:
      instance-id: gateway-9527.com
      prefer-ip-address: true
  zuul:
    routes:
      aigouUser.serviceId: EMPLOYEE-PROVIDER
      aigouUser.path:  /employee/**
    ignored-services: "*"
    prefix: /aigou   # 访问前缀
---
spring:
  profiles: test
  application:
    name: MICROSERVICE-ZUUL-TEST
server:
  port: 9528
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: gateway-9527.com
    prefer-ip-address: true
zuul:
  routes:
    aigouUser.serviceId: EMPLOYEE-PROVIDER
    aigouUser.path:  /employee/**
  ignored-services: "*"
  prefix: /aigou   # 访问前缀
